[build]
  publish = "."

[[redirects]]
  from = "/commercial-consulting"
  to = "/commercial-consulting.html"
  status = 200

[[redirects]]
  from = "/consumer-consulting"
  to = "/consumer-consulting.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
